name: Build and Deploy
on: [push]
jobs:
  build-and-deploy:
    concurrency: ci-${{ github.ref }} # Recommended if you intend to make multiple deployments in quick succession.
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2

      - name: Install and Build 🔧 # This example project is built using npm and outputs the result to the 'build' folder. Replace with the commands required to build your project, or remove this step entirely if your site is pre-built.
        env: |
          REACT_APP_MAPBOX_ENV= ${{ secrets.REACT_APP_MAPBOX_ENV }}
          REACT_APP_GRAPHQL_URI= ${{ secrets.REACT_APP_GRAPHQL_URI }}
        run: |
          yarn install --frozen-lockfile
          yarn run build
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4.2.2
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: build # The folder the action should deploy.
